BRS for APIM to enable secure access
azsk/AzTS-docs pull request #117
Opened 2021-10-29 07:15 UTC by pranchalsomani

2021-11-01 08:17 UTC, gvaradarajan-msft requested changes

2021-11-01 08:17 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +                $listOfApiRemediated = @()
Please change this and the below line to listOfApi**s***.

2021-11-01 08:17 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +                        $output = (Get-AzAPIManagementAPI -Context $apiMgmtContext -ApiId $_.ApiId  -ErrorAction SilentlyContinue).Protocols
Do we really need to execute another command to get the status? Please check if `Set-AzAPIManagementAPI` returns the state of the resource post the update.
Else, we can rely on the output of this command to determine if the command was a success/failure - Unless, you saw an issue where `Set-AzAPIManagementAPI()` succeeded, but, `Get..` returned a different output than the `Set..`.

2021-11-01 08:17 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +
Please delete the stray newline.
`$output` will be a list of protocols. Please confirm this.

2021-11-01 08:17 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +                if($listOfApiRemediated.count -ne '0')
`List.Count` should be returning an integer. Please check. This needs to be done in the below `if` block as
 well.

2021-11-01 08:17 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +                                                                                            @{N='ListOfAPIRemediated';E={$listOfApiRemediated}}
`ListOfAPIRemediated` to be replaced with `ListOfAPIsRemediated`. This needs to be done below as well - in the below `if` and `catch` blocks.

2021-11-01 08:17 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +                    $listOfApiRemediated = $listOfApiRemediated -join ","
Also, even if there is one `skipped` API in an APIM resource, the resource remediation should be treated as an error/incomplete.

2021-11-01 08:34 UTC, gvaradarajan-msft requested changes

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +function Disable-HTTPSUrlSchemeForAPIsOfAPIManagementServices
Please fix this after finalizing the file name / remediation command.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +        .EXAMPLE
How is this command different from the above?

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +    $apiManagementServiceDetails | ForEach-Object{
Can this filtering be done similar to L251. That is, combine L608 and L610.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +    $backupFolderPath = "$([Environment]::GetFolderPath('LocalApplicationData'))\AzTS\Remediation\Subscriptions\$($context.Subscription.SubscriptionId.replace('-','_'))\$($(Get-Date).ToString('yyyyMM
Please fix the file name `Url` vs `HTTPS`, and also to reflect the other file name related modifications being done in the remediation command.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +        $apiManagementservice = $_
Please rename the variable from `apiManagementservice` to `apiManagementService`.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +            $listOfApiRolledBack = @()
Please change this and the below variable to listOfApi**s***.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +            #$$apiManagementservice.ListOfAPIRemediated
Please delete this if not required.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +                    if($output -eq "Http")
`$output` will be a list of protocols. Please confirm this.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +                    $output = (Get-AzAPIManagementAPI -Context $apiMgmtContext -ApiId $_.ApiId  -ErrorAction SilentlyContinue).Protocols
Do we really need to execute another command to get the status? Please check if `Set-AzAPIManagementAPI` returns the state of the resource post the update.
Else, we can rely on the output of this command to determine if the command was a success/failure - Unless, you saw an issue where `Set-AzAPIManagementAPI()` succeeded, but, `Get..` returned a different output than the `Set..`.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +            if($listOfApiRolledBack.count -ne '0')
`List.Count` should be returning an integer. Please check. This needs to be done in the below `if` block as
 well.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +                                                                                        @{N='ListOfAPIRolledBack';E={$listOfApiRolledBack}}
`ListOfAPIRolledBack` to be replaced with `ListOfAPIsRolledBack`. A similar change needs to be done for the `skipped` case below.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +            if($listOfApiSkipped.count -ne '0')
Even if there is one `skipped` API in an APIM resource, the resource rollback should be treated as an error/incomplete.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +            Write-Host "Skipping this API Management Service. HTTPS url scheme will not be enabled for any of the API(s) of this service." -ForegroundColor $([Constants]::MessageType.Error)
We are disabling HTTPS here.

2021-11-01 08:34 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +            $apiManagementServiceRolledBackFile = "$($backupFolderPath)\RolledBackApiManagementServices.csv"
Ideally it is this file name convention that needs to be followed everywhere. Please use this as a reference for your changes.

2021-11-01 12:10 UTC, pranchalsomani commented on Scripts/RemediationScripts/Remediate-EnableHTTPSUrlSchemeForAPIManagementServices.ps1
> +           Enable-HTTPSUrlSchemeForAPIsOfAPIManagementServices -SubscriptionId 00000000-xxxx-0000-xxxx-000000000000 -PerformPreReqCheck -DryRun
done

2021-11-02 07:20 UTC, gvaradarajan-msft requested changes

2021-11-02 07:20 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSForAPIsInAPIManagementServices.ps1
> +               $listOfApisRemediated = @()
NIT: Please fix the indentation.

2021-11-02 07:20 UTC, gvaradarajan-msft commented on Scripts/RemediationScripts/Remediate-EnableHTTPSForAPIsInAPIManagementServices.ps1
> +                $apiMgmtContext = New-AzAPIManagementContext -ResourceGroupName $ResourceGroupName -ServiceName $_.ResourceName
The variable in L383 is `$resourceGroupName` - starts with a lower case, unlike `$ResourceGroupName`.

2021-11-08 05:57 UTC, gvaradarajan-msft approved these changes

2021-11-08 05:58 UTC, merged