Updated secure template for Azure VM (Windows/Linux)
azsk/AzTS-docs pull request #207
Opened 2022-04-04 12:40 UTC by TarunKrShukla

2022-04-04 15:42 UTC, MSFT-Chirag approved these changes

2022-04-05 05:15 UTC, VamseeInala commented on 08-Secure by default/Secure Templates/Bicep/VirtualMachine.bicep
> +resource vm 'Microsoft.Compute/virtualMachines@2021-03-01' = {
Let's use the latest version: 2021-11-01

2022-04-05 05:16 UTC, VamseeInala requested changes
Can you please check the versions of the resources and upgrade to the latest?

2022-04-05 07:17 UTC, VamseeInala approved these changes

2022-04-05 07:17 UTC, merged