Rediscache disable NonSSL ports BRS
azsk/AzTS-docs pull request #229
Opened 2022-05-20 13:16 UTC by Aboli-msft

2022-05-23 10:24 UTC, VamseeInala requested changes
@Aboli-msft Can you please check my comments and accommodate them as required?

2022-05-23 10:24 UTC, VamseeInala commented on Scripts/RemediationScripts/Remediate-DisableNonSSLPortOnRedisCache.ps1
> +    Write-Host "*** To Disable Non-SSL port on Redis Cache in a Subscription, Contributor or higher privileges on the Redis Cache are required.***" -ForegroundColor $([Constants]::MessageType.Info)
Can we modularize the control specific code into a different method from the common code?

2022-05-23 10:24 UTC, VamseeInala commented on Scripts/RemediationScripts/Remediate-DisableNonSSLPortOnRedisCache.ps1
> +    $context = Set-AzContext -SubscriptionId $SubscriptionId -ErrorAction Stop
Can we add checks to avoid this call if the context is already set to the intended subscription?

2022-05-31 06:27 UTC, VamseeInala approved these changes

2022-05-31 06:38 UTC, pranchalsomani approved these changes

2022-05-31 06:39 UTC, merged