Users/pranchal/bastion tbv9
azsk/AzTS-docs pull request #367
Opened 2023-06-14 14:34 UTC by pranchalsomani

2023-06-21 11:08 UTC, jaiswalricha approved these changes

2023-06-22 11:18 UTC, aakashpahwa-msft requested changes

2023-06-22 11:18 UTC, aakashpahwa-msft commented on Control coverage/Feature/Bastion.md
> +>   - Bastion sku is of type "basic".
Basic* right?

2023-06-22 11:18 UTC, aakashpahwa-msft commented on Control coverage/Feature/Bastion.md
> +The Bastion Shareable link let users with local credentials to bypass primary authentication to Azure, MFA requirements and Network Segmentation by allowing direct connectivity to VMs using the link
lets* users

2023-06-22 11:18 UTC, aakashpahwa-msft commented on Control coverage/Feature/Bastion.md
> +   "To delete all the shareable links: Go to Azure Portal --> Select your Bastion --> Settings blade --> 'Shareable links' --> select all the VMs with links --> Click 'Delete' and to disable shareabl
Separate the two things to be done (delete existing links and disable shareable link) on two separate lines.
Sentence is ending with comma - please fix

2023-06-29 17:34 UTC, merged