Adding BRS for AI Search service RBAC only API access
azsk/AzTS-docs pull request #429
Opened 2024-04-08 11:24 UTC by Aboli-msft

2024-04-10 20:36 UTC, p-saga commented on Scripts/RemediationScripts/Remediate-ConfigureRoleBasedAPIAcessOnlyForAISearch.ps1
> +    $validAISearchServices | ForEach-Object {
Is the $resourceList created in line 827 supposed to be used here instead of $validAISearchServices?
The resourceList isn't used anywhere.

2024-04-10 20:36 UTC, p-saga commented on Scripts/RemediationScripts/Remediate-ConfigureRoleBasedAPIAcessOnlyForAISearch.ps1
> +            if(($res.CurrentDisableLocalAuth -ne $true))
$res.CurrentDisableLocalAuth is equal to true then $AISearchservicesWithRBACOnlyAPIAccess should be populated right?

2024-04-12 08:42 UTC, p-saga commented on Scripts/RemediationScripts/Remediate-ConfigureRoleBasedAPIAcessOnlyForAISearch.ps1
> +                Write-Host "Valid resource id(s) not found in input json file. Error: [$($_)]" -ForegroundColor $([Constants]::MessageType.Error)
As discussed, please have a look at the message to logged.

2024-04-12 13:01 UTC, jaiswalricha approved these changes

2024-04-12 13:27 UTC, p-saga commented on Scripts/RemediationScripts/Remediate-ConfigureRoleBasedAPIAcessOnlyForAISearch.ps1
> +            Write-Host "API access set as RBAC only for for [$($totalAISearchservicesRemediated)] out of [$($totalAISearchServiceWithoutRBACOnlyAPIAccess)] Azure AI Search services " -ForegroundColor
Typo: for [$($totalAISearchservicesRemediated)]

2024-04-12 13:28 UTC, p-saga commented on Scripts/RemediationScripts/Remediate-ConfigureRoleBasedAPIAcessOnlyForAISearch.ps1
> +        Write-Host "[Step 5 of 5] Setting RBAC only API access for Azure AI Search services)"
Typo: Remove bracket at the end.

2024-04-12 13:29 UTC, p-saga requested changes
Added 2 comments for Typo. Approving with suggestions.

2024-04-12 13:31 UTC, p-saga approved these changes

2024-04-12 13:35 UTC, merged