Control spec update- Kunernetes
azsk/AzTS-docs pull request #82
Opened 2021-08-31 19:28 UTC by Aboli-msft

2021-09-08 17:27 UTC, TarunKrShukla requested changes
Changes needed as per comments.

2021-09-08 17:27 UTC, TarunKrShukla commented on Control coverage/Feature/KubernetesService.md
> +|<b>ControlId:</b><br>Azure_KubernetesService_Audit_Enable_Monitoring<br><b>DisplayName:</b><br>Monitoring must be enabled for Azure Kubernetes Service.<br><b>Description: </b><br>Monitoring must be
Plz dont user '.' fullstop for displayName or description.

2021-09-08 17:27 UTC, TarunKrShukla commented on Control coverage/Feature/KubernetesService.md
> +|<b>ControlId:</b><br>Azure_KubernetesService_Audit_Enable_Monitoring<br><b>DisplayName:</b><br>Monitoring must be enabled for Azure Kubernetes Service.<br><b>Description: </b><br>Monitoring must be
ARM API to list Container Services at subscription level , looks this is copy paste error in all controls
This should be changed to Kubernetes Services

2021-09-08 17:27 UTC, TarunKrShukla commented on Control coverage/Feature/KubernetesService.md
> +|<b>ControlId:</b><br>Azure_KubernetesService_NetSec_Dont_Open_Management_Ports<br><b>DisplayName:</b><br>Do not leave management ports open on Kubernetes nodes.<br><b>Description: </b><br>Do not lea
No properties are mentioned for this control, Also there are typos in Control speclet column.

2021-09-08 17:27 UTC, TarunKrShukla commented on Control coverage/Feature/KubernetesService.md
> +|<b>ControlId:</b><br>Azure_KubernetesService_Deploy_Use_Latest_Version<br><b>DisplayName:</b><br>Kubernetes Services should be upgraded to a non-vulnerable Kubernetes version.<br><b>Description: </b
Two full stops in control spec-let

2021-09-08 17:27 UTC, TarunKrShukla commented on Control coverage/Feature/NotificationHub.md
> +|-----------|-------------------------------------|------------------|
Plz don't use fullstop '.' in display name and description.

2021-09-08 17:27 UTC, TarunKrShukla commented on Control coverage/Feature/NotificationHub.md
> +| <b>ControlId:</b><br>Azure_NotificationHub_AuthZ_Dont_Use_Manage_Access_Permission	<br><b>DisplayName:</b><br>Access policies on Notification Hub must not have Manage access permissions.<br><b>Desc
If there are multiple properties for a give API, use comma ',' to separate them instead of newline.

2021-12-05 12:21 UTC, VishalHaibatpure commented
@Aboli-msft: Do we need to drop this PR as we have moved to new format?

2021-12-07 04:25 UTC, Aboli-msft commented
With new format this PR is not needed

2021-12-07 04:25 UTC, closed without merging