Control Spec update CloudService ,CosmosDB
azsk/AzTS-docs pull request #84
Opened 2021-09-03 04:31 UTC by Aboli-msft

2021-09-08 17:15 UTC, TarunKrShukla requested changes

2021-09-08 17:15 UTC, TarunKrShukla commented on Control coverage/Feature/CloudService.md
> +| <b>ControlId:</b><br>Azure_CloudService_DP_DontAllow_HTTP_Access_InputEndpoints<br><b>DisplayName:</b><br>Encrypt data in transit for Cloud service role <br><b>Description: </b><br> Cloud Service m
Looks like there is typo in Properties [name: 'properties.inputEndpoints.protocol]

2021-09-08 17:15 UTC, TarunKrShukla commented on Control coverage/Feature/CloudService.md
> +| <b>ControlId:</b><br>Azure_CloudService_SI_Auto_OSUpdate<br><b>DisplayName:</b><br>Set automatic update for Cloud Service OS version<br><b>Description: </b><br> Set automatic update for Cloud Servi
If there are multiple properties please use space after each property.

2021-09-08 17:15 UTC, TarunKrShukla commented on Control coverage/Feature/CloudService.md
> +| <b>ControlId:</b><br>Azure_CloudService_DP_DontAllow_HTTP_Access_InputEndpoints<br><b>DisplayName:</b><br>Encrypt data in transit for Cloud service role <br><b>Description: </b><br> Cloud Service m
Also in API we might want to add API to get slot or roles.

2021-09-08 17:15 UTC, TarunKrShukla commented on Control coverage/Feature/CloudService.md
> +| <b>ControlId:</b><br>Azure_CloudService_SI_Auto_OSUpdate<br><b>DisplayName:</b><br>Set automatic update for Cloud Service OS version<br><b>Description: </b><br> Set automatic update for Cloud Servi
Also in API we might want to add API to get slot or roles.

2021-09-08 17:15 UTC, TarunKrShukla commented on Control coverage/Feature/CosmosDB.md
> +| <b>ControlId:</b><br>Azure_CosmosDB_Enable_Adv_Threat_Protection<br><b>DisplayName:</b><br>Enable Threat detection for CosmosDB database<br><b>Description: </b><br> Threat Protection for Azure Cosm
In property column 'name:' can be removed for all controls

2021-10-01 11:24 UTC, TarunKrShukla commented on Control coverage/Feature/CosmosDB.md
> +## Cloud Service
This heading should be CosmosDB

2021-10-01 11:24 UTC, TarunKrShukla commented on Control coverage/Feature/CosmosDB.md
> +## Cloud Service
Also in main page link need to be added for CosmosDB, as it's a new service.

2021-11-24 18:00 UTC, closed without merging

2021-11-24 18:00 UTC, Aboli-msft commented
PR no more required . Control spec updated with latest format